
server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/safwahcareers
    username: shuaibu
    password: password
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    show-sql: true